from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, runtime_checkable


class DuplicateUserError(RuntimeError):
    pass


@dataclass(frozen=True)
class SavedAssessmentRow:
    kind: str
    aid: str
    label: str
    created: str


@runtime_checkable
class AccountRepository(Protocol):
    """Persistence contract for web identity/session/history state."""
    def user_for_session(self, token: str, now_iso: str) -> int | None: ...
    def saved_exists(self, user_id: int, kind: str, aid: str) -> bool: ...
    def load_saved(self, user_id: int, kind: str, aid: str) -> str | None: ...
    def save_bounded(self, user_id: int, kind: str, aid: str, label: str, blob: str, limit: int = 100) -> None: ...
    def previous_saved_blob(self, user_id: int, kind: str, aid: str, label: str) -> str | None: ...
    def create_user(self, email: str, password_hash: str) -> int: ...
    def find_user(self, email: str) -> tuple[int, str] | None: ...
    def update_password(self, user_id: int, password_hash: str) -> None: ...
    def replace_session(self, user_id: int, token: str, expires: str) -> None: ...
    def delete_session(self, token: str) -> None: ...
    def list_saved(self, user_id: int) -> tuple[SavedAssessmentRow, ...]: ...
