from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Protocol, runtime_checkable


class DuplicateUserError(RuntimeError):
    pass


@dataclass(frozen=True)
class SavedAssessmentRow:
    kind: str
    aid: str
    label: str
    created: str
    archived_at: str | None = None
    deleted_at: str | None = None


@dataclass(frozen=True)
class AuditEntry:
    user_id: int
    action: str
    kind: str
    aid: str
    at: str
    detail: str = ""


def retention_cutoff(now_iso: str, retention_days: int) -> str:
    """ISO timestamp; items soft-deleted at or before it are outside the retention window."""
    return (datetime.fromisoformat(now_iso) - timedelta(days=max(0, int(retention_days)))).isoformat()


@runtime_checkable
class AccountRepository(Protocol):
    """Persistence contract for web identity/session/history state."""
    def user_for_session(self, token: str, now_iso: str) -> int | None: ...
    def saved_exists(self, user_id: int, kind: str, aid: str) -> bool: ...
    def load_saved(self, user_id: int, kind: str, aid: str) -> str | None: ...
    def save_bounded(self, user_id: int, kind: str, aid: str, label: str, blob: str, limit: int = 100) -> None: ...
    def previous_saved_blob(self, user_id: int, kind: str, aid: str, label: str) -> str | None: ...
    def create_user(self, email: str, password_hash: str) -> int: ...
    def find_user(self, email: str) -> tuple[int, str] | None: ...
    def update_password(self, user_id: int, password_hash: str) -> None: ...
    def replace_session(self, user_id: int, token: str, expires: str) -> None: ...
    def delete_session(self, token: str) -> None: ...
    def list_saved(self, user_id: int, *, query: str = "", kind: str = "", date_from: str = "", date_to: str = "",
                   archived: bool | None = None, deleted: bool = False) -> tuple[SavedAssessmentRow, ...]: ...
    def get_saved_meta(self, user_id: int, kind: str, aid: str) -> SavedAssessmentRow | None: ...
    # Lifecycle: every call is owner-scoped (user_id match) and returns False/empty for anyone else's item.
    def rename_saved(self, user_id: int, kind: str, aid: str, label: str, now_iso: str) -> bool: ...
    def set_archived(self, user_id: int, kind: str, aid: str, archived: bool, now_iso: str) -> bool: ...
    def soft_delete_saved(self, user_id: int, kind: str, aid: str, now_iso: str) -> bool: ...
    def restore_saved(self, user_id: int, kind: str, aid: str, now_iso: str, retention_days: int) -> bool: ...
    def purge_saved(self, user_id: int, kind: str, aid: str, now_iso: str) -> bool: ...
    def purge_expired(self, now_iso: str, retention_days: int) -> tuple[tuple[int, str, str], ...]: ...
    def record_audit(self, user_id: int, action: str, kind: str, aid: str, now_iso: str, detail: str = "") -> None: ...
    def list_audit(self, user_id: int, limit: int = 20) -> tuple[AuditEntry, ...]: ...
